export enum DocumentType {
  PROFILE_PICTURE = 'PROFILE_PICTURE',
  ID_DOCUMENT = 'ID_DOCUMENT',
  LICENSE = 'LICENSE',
  PROOF_OF_ADDRESS = 'PROOF_OF_ADDRESS',
  CONTRACT = 'CONTRACT',
  MESSAGE_ATTACHMENT = 'MESSAGE_ATTACHMENT',
  CONSULTATION_FILE = 'CONSULTATION_FILE',
  OTHER = 'OTHER',
}
